update workflow

diff --git a/.github/workflows/create-AMI.yml b/.github/workflows/create-AMI.yml
--- a/.github/workflows/create-AMI.yml
+++ b/.github/workflows/create-AMI.yml
@@ -104,6 +104,11 @@ jobs:
             echo "Instance refresh status: $instance_refresh_status"
             sleep 10
             instance_refresh_status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{vars.AUTO_SCALING_GROUP_NAME}} --region ${{secrets.AWS_REGION}} --query 'InstanceRefreshes[?StartTime!=`null`] | sort_by(@, &StartTime)[-1].Status' --output text)
+            if [ "$instance_refresh_status" == "Failed" || "$instance_refresh_status" == "Cancelled" ]
+            then
+              echo "Instance refresh failed or cancelled"
+              exit 1
+            fi
           done
           echo "Instance refresh status: $instance_refresh_status"
           echo "Instance refresh completed successfully"
