Assignment06 (#32)
* Minor chnages to API's , to fix some issue

* Fetching AMI ID using secrets

* Fixed code to run create ami on merge

* Test commit

* Test commit

* Added code to remove installation of mariadb in AMI

* Test commit

* Removed code to move env file

* Adding Systemd file to create web-application serivce

* Fixed Path issue

* Modified systemd file to use environment file

* Added code to change the environment file path

* Test commit

* Change file permisons for environment file

* Updated file name and permissions

* Formatting issue

* Packer format issue

* Fixed classcast issue

* Updated github action

* Test commit for packer format

* Updated github action file, with correct filepath

* Formatted packer file

diff --git a/.github/workflows/run-packer-validation.yml b/.github/workflows/run-packer-validation.yml
--- a/.github/workflows/run-packer-validation.yml
+++ b/.github/workflows/run-packer-validation.yml
@@ -26,7 +26,14 @@ jobs:
         run: packer init ./packer/.
 
       - name: Packer format
-        run : packer fmt ./packer/.
+        run : |
+          # Run packer fmt and capture the output
+          output=$(packer fmt -check=true -write=false ./packer/.)
+          if [ -n "$output" ]; then
+            echo "Packer format check failed. Please run 'packer fmt' to fix the formatting issues."
+            echo "$output"
+            exit 1
+          fi
 
       - name: Packer Validate
         run : packer validate ./packer/.
